// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ymufscicqfmkimfivodl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InltdWZzY2ljcWZta2ltZml2b2RsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMwNzY3NTIsImV4cCI6MjA1ODY1Mjc1Mn0.NeUypwTOXHeOkyH-6UKjRaf0l-pW8L045Sy8ZzTT5vU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);